In [64]:
import numpy as np
import random
import cPickle
import gzip
import pandas as pd
from sklearn.cross_validation import train_test_split

In [65]:
bbc = pd.read_csv('data/supervisedlearningdataset_13082016.csv', parse_dates=True)

# converting NaN values in the dataset to 0.
for column in bbc.columns:
    bbc[column] = bbc[column].fillna(0)

# removing document id from dataset.
bbc = bbc.drop("Document id", 1)

# target variable.
target = "label"

# seperating data into features and label
y = bbc.pop(target)
X = bbc
# splitting data into train and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

training_data_train, validation_data_train, training_data_test, validation_data_test = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

In [24]:
np_bbc = np.array(bbc)

In [25]:
np_bbc

array([[ 0.02356175,  0.15461793,  0.07521923, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.04372118, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.13512836,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  4.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  4.        ],
       [ 0.        ,  0.00818316,  0.        , ...,  0.        ,
         0.        ,  4.        ]])

In [26]:
f = gzip.open('./data/mnist.pkl.gz', 'rb')
training_data, validation_data, test_data = cPickle.load(f)
f.close()
training_data

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
 array([5, 0, 4, ..., 8, 4, 8]))

In [59]:
bbc.shape

(2225, 9636)